#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
service nginx restart