#!/usr/bin/env bash
# Bash script configures a new Ubuntu machine to match the task requirements
sudo apt-get -y upgrade
sudo apt-get -y update
sudo apt-get -y install nginx

echo "Holberton School" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
str="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"
str1="\n\tadd_header X-Served-By \$HOSTNAME;"
str2="\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/server_name _;/$str$str1$str2/" /etc/nginx/sites-available/default
sudo service nginx start