#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd.
while IFS=':' read -r USERNAME PASSWORD ID GROUP_ID INFO HOME_DIRECTORY SHELL
do 
echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY \
and rides $SHELL. $ID's place is protected by the passcode $PASSWORD, more info \
about the user here: $INFO"
done < /etc/passwd